# Generated by Django 5.2.6 on 2026-01-04 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Tipo de Documento"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tipos de Documentos",
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leido_por_ia",
                    models.BooleanField(default=False, verbose_name="Leído por IA"),
                ),
                (
                    "realizado_por",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        null=True,
                        verbose_name="Realizado por",
                    ),
                ),
                (
                    "grupos_criminales",
                    models.BooleanField(
                        default=False, verbose_name="Involucra grupos criminales"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="Narración"
                    ),
                ),
                (
                    "nro_sgsp",
                    models.CharField(
                        blank=True, max_length=220, null=True, verbose_name="Nro. SGSP"
                    ),
                ),
                ("fecha_informe", models.DateField(verbose_name="Fecha del Informe")),
                ("asunto", models.CharField(max_length=220, verbose_name="Asunto")),
                (
                    "informe",
                    models.FileField(
                        null=True,
                        upload_to="documento/informes/",
                        verbose_name="Informe",
                    ),
                ),
                (
                    "informe_editable",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documento/informes_editables/",
                        verbose_name="Informe Editable (opcional)",
                    ),
                ),
                (
                    "texto_extraido",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Texto extraído automáticamente",
                    ),
                ),
                (
                    "fecha_ingresada",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Ingreso"
                    ),
                ),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "creada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "dependencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.dependencia",
                        verbose_name="Dependencia",
                    ),
                ),
                (
                    "tipo_doc",
                    models.ForeignKey(
                        default=3,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.tipodoc",
                        verbose_name="Tipo de documento",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Documentos",
                "ordering": ["-fecha_ingresada"],
                "permissions": [
                    (
                        "puede_preguntar_ia",
                        "Puede realizar consultas de IA sobre documentos",
                    )
                ],
            },
        ),
    ]
