# Generated by Django 4.2.4 on 2026-01-06 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("documentos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documento",
            name="grupos_criminales",
        ),
        migrations.RemoveField(
            model_name="documento",
            name="nro_sgsp",
        ),
        migrations.RemoveField(
            model_name="documento",
            name="realizado_por",
        ),
        migrations.AlterField(
            model_name="documento",
            name="dependencia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dependencia",
                verbose_name="Área/Departamento",
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="descripcion",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Descripción"
            ),
        ),
    ]
