"""
Django settings for argos project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--u7d8la7r0i(6kx52$(8-o7t0t2w=znchytx3o6gqj1lmu!-6a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

GDAL_LIBRARY_PATH = r'C:\OSGeo4W\bin\gdal308.dll'  # Asegúrate de usar la versión correcta de la dll
os.environ['GDAL_LIBRARY_PATH'] = GDAL_LIBRARY_PATH

GEOS_LIBRARY_PATH = 'C:\OSGeo4W\\bin\geos_c.dll'


ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Expiración absoluta (aunque haya actividad)
SESSION_COOKIE_AGE = 1800  # 30 minutos (en segundos)

# Expiración por inactividad
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # opcional, se cierra al cerrar navegador

# Para inactividad estricta (se renueva en cada request):
SESSION_SAVE_EVERY_REQUEST = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.gis",
    "djgeojson",
    'core',
    'simple_history',
    "leaflet",
    'django_filters',
    "documentos",
    "django_user_agents",
    "axes",
]


AUTH_USER_MODEL = "core.Usuario"

MIDDLEWARE = [
    "axes.middleware.AxesMiddleware", 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "simple_history.middleware.HistoryRequestMiddleware",

]

# Configuración básica
AXES_FAILURE_LIMIT = 5  # cantidad máxima de intentos
AXES_COOLOFF_TIME = 1   # horas de bloqueo
AXES_LOCKOUT_PARAMETERS = ["username", "ip_address"]


MESSAGE_TAGS = {
    messages.DEBUG: 'alert-dark',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}


ROOT_URLCONF = 'argos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries':{
                'simple': 'core.templatetags.mytemplatetags',
            }
        },
    },
]

WSGI_APPLICATION = 'argos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        "NAME": "xxxdoc",        # nombre de tu base
        "USER": "postgres",      # usuario postgres
        "PASSWORD": "xxxxx", # clave postgres
        "HOST": "localhost",       # o la IP del servidor
        "PORT": "5432",            # puerto por defecto de PostgreSQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Montevideo'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = "/documentos/"
LOGIN_URL = "/login/"
LOGOUT_REDIRECT_URL = "/login/"

AUTH_USER_MODEL = "core.Usuario"

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",  # nuevo
    "django.contrib.auth.backends.ModelBackend",
]